<img src="https://comp116sp19.cs.unc.edu/images/COMP116Logo.png" style="display:inline; width:200px" />

# Assignment 5: 311 Database

These data were scraped from the 311 Service Request data available from the [New York City Open Data site](https://nycopendata.socrata.com/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9). The data are presented to you in four arrays each with **N** rows representing service requests over a period of about 4 weeks of full days.
 
**Times:** N by 3 integer array of the _Day_ (counting from 0), _Hour_ (0 to 23), and _Day of the Week_ (Monday is 0) the request was created.
 
**Requests:** N by 2 string array of the _Complaint_ and the _Descriptor_ for the request.
 
**Locations:** N by 2 string array of the _City_ and _[Borough](https://en.wikipedia.org/wiki/Borough)_ for the request.
 
**Coordinates:** N by 2 float array of the _X_ and _Y_ coordinates of the request in the [State Plane Coordinate system](https://en.wikipedia.org/wiki/State_Plane_Coordinate_System). You won't need to know anything about the coordinate system, just that they are two orthogonal coordinates in the plane. 
 
Think of the 4 arrays as representing one large table with the **N** rows and 9 columns. 

## Set up

I will set up the environment for you here.

In [1]:
%matplotlib inline
%autosave 15
import numpy as np
import pylab
import comp116
import pickle

check, report = comp116.start('A5')
with open('A5data.pickle', 'rb') as fid:
    Times, Requests, Locations, Coordinates = pickle.load(fid)
Times.flags.writeable = False
Requests.flags.writeable = False
Locations.flags.writeable = False
Coordinates.flags.writeable = False

Autosaving every 15 seconds


ModuleNotFoundError: No module named 'comp116'

In [5]:
import pickle
with open('A5data.pickle', 'rb') as fid:
    Times, Requests, Locations, Coordinates = pickle.load(fid)

## Fill out information on userid/collaborators

In [3]:
Author = 'mdubois6' # not your pid, your onyen
Collaborators = []

In [4]:
check('Author', Author != 'youronyen', points=1)
check('Collaborators', Collaborators != ['list', 'their', 'onyens', 'here'], points=1)

Author appears correct
Collaborators appears correct


## 1. How many requests do we have?

I'm looking for **N** as in the description above.

In [5]:
#Write your code here
A1 = len(Times)

print('Number of requests =', A1)

Number of requests = 14204


In [6]:
check('A1', A1, points=5)

A1 appears correct


## 2. What was the average number of requests per hour?

In [10]:
print(Times[:,1])

[ 0  0  0 ... 23 23 23]


In [14]:
#Write your code here
A2 = []
for requests in Times[:,1]:
    np.count(0)
    #for times in range(0,24):
        
        #print('Requests/hour =', A2)

AttributeError: module 'numpy' has no attribute 'count'

In [ ]:
check('A2', A2, points=5)

## 3. Which cities are in the data?

I want an alphabetized list of the different values in the city column of the locations. Each city name should be in the list only once.

In [15]:
#Write your code here

def setOfUniqueWordsInList( names ):
    '''
    Given a Python list of names, return the set of the unique words
    '''
    return sorted(set(names[:,0]))

A3 = setOfUniqueWordsInList( Locations )

print('Cities =', A3)

Cities = ['Arverne', 'Astoria', 'Bayside', 'Bellerose', 'Bronx', 'Brooklyn', 'Cambria Heights', 'Central Park', 'College Point', 'Corona', 'East Elmhurst', 'Elmhurst', 'Far Rockaway', 'Floral Park', 'Flushing', 'Forest Hills', 'Fresh Meadows', 'Glen Oaks', 'Hollis', 'Howard Beach', 'Jackson Heights', 'Jamaica', 'Kew Gardens', 'Little Neck', 'Long Island City', 'Maspeth', 'Middle Village', 'New Hyde Park', 'New York', 'Oakland Gardens', 'Ozone Park', 'Queens', 'Queens Village', 'Rego Park', 'Richmond Hill', 'Ridgewood', 'Rockaway Park', 'Rosedale', 'Saint Albans', 'South Ozone Park', 'South Richmond Hill', 'Springfield Gardens', 'Staten Island', 'Sunnyside', 'Whitestone', 'Woodhaven', 'Woodside']


In [16]:
check('A3', A3, points=8)

A3 appears correct


## 4. Which complaints happened every day?

Your result should be an alphabetical list of complaints that occur every day in the data. In other words, if there is even a single day without a particular complaint, that complaint should not be in your list. Each complaint should only be in the list once.

In [26]:
#Write your code here
A4 = []
request_data = Requests[:,0]
days = Times[:,0]
for complaints in range(len(request_data)):# expecting a list of strings
    for times in range(len(days)):
    print('Complaints that happened every day', A4)

IndentationError: expected an indented block (<ipython-input-26-50ede019f940>, line 7)

In [ ]:
check('A4', A4, points=16)

## 5. Which time had the most requests?

Your result should be a two-element array of the day and hour of the time that had the most requests.

In [ ]:
#Write your code here
A5 = np.array([0, 0])


print('Most requests [Day Hour] =', A5)

In [ ]:
check('A5', A5, points=16)

## 6. Where are the parties?

Which city has the most requests with descriptor 'Loud Music/Party'?

In [6]:
Descriptor = 'Loud Music/Party'

#Write your code here
A6 = Requests[:,1]


print('Party city =', A6)

Party city = ['No Access' 'Loud Music/Party' 'Loud Music/Party' ... 'No Access'
 'Loud Music/Party' 'Partial Access']


In [ ]:
check('A6', A6, points=16)

## 7. Where are they drinking in the Bronx?

Plot points at the coordinates of the requests with borough 'Bronx' and complaint 'Drinking'.

Do **not** augment the plot in any way. No titles, etc. 

In [ ]:
Borough = 'Bronx'
Complaint = 'Drinking'

#Write your code here

#These lines format the graph to make it look nicer, no need to change them
pylab.axes().set_aspect('equal', 'datalim')
pylab.grid()

# DO NOT TOUCH THIS LINE
A7_plot = pylab.gcf()

In [ ]:
check('A7', A7_plot, points=16)

## 8. Where is the most blocked driveway?

I want the coordinate that has the most requests with complaint 'Blocked Driveway'? I'm expecting a two-element float array with the X/Y coordinate of the driveway with the most complaints.

In [2]:
Complaint = 'Blocked Driveway'

# Write your code here
A8 = np.zeros(2)

print('Most blocked coordinate =', A8)

Most blocked coordinate = [0. 0.]


In [ ]:
check('A8', A8, points=16)

## Done!

Now get your report and submit your assignment.

## Saving your work
<img src="saveAndCheckpoint.png" width="300" style="float: right" />

Now save your work by going to (menu <font color='green'>File</font>-><font color='green'>Save and Checkpoint</font>)

In [7]:
report(Author, Collaborators)
print('The submit button for the assignment is in the unlocker notebook')

NameError: name 'report' is not defined

## Close this notebook and then go back to the AssignmentUnlocker
<img src="closeAndHalt.png" width="300" style="float: right" />

Before going back to the AssignmentUnlocker and submit your work, you'll need to go close this
notebook (menu <font color='green'>File</font>-><font color='green'>Close and Halt</font>.)


Note that if you actually saved your work you should not see the leaving site message below.
If you do see the `Leave Site` warning, cancel and save your work again.
<br />
<img src="leaveSite.png" width="300" style="float: left" />

In [ ]:
#Q4

In [9]:
def compaintsEachDay(times, requests, locations, coordinates):
    
    ndays = times[-1,0] + 1
    
    reqs = []
    for i in range(ndays): 
        reqs.append(set())
        

    for i in range(len(times)):
        complaint = requests[i,0]
        d = times[i,0]
        reqs[d].add(complaint)
        
    return sorted(set.intersection(*reqs))
    #End

print('Complaints that happened every day', compaintsEachDay(Times, Requests, Locations, Coordinates))

Complaints that happened every day ['Blocked Driveway', 'Derelict Vehicle', 'Illegal Parking', 'Noise - Commercial', 'Noise - Street/Sidewalk', 'Noise - Vehicle', 'Traffic', 'Vending']


In [ ]:
#Q5

In [11]:
def dayHourTime(times, requests, locations, coordinates):
  
 
    rph = np.bincount(times[:,0]*24 + times[:,1])
    #print(rph)
    i = np.argmax(rph)
    return np.array([i//24, i%24])
    #End

A5 = dayHourTime(Times, Requests, Locations, Coordinates)
print('Most requests happened on day', A5[0], 'hour', A5[1])

Most requests happened on day 13 hour 23


In [ ]:
#Q6

In [12]:
def whichCity(complaint, times, requests, locations, coordinates):

    isDescriptor = requests[:,1] == complaint
    counts = {}
    for city in locations[isDescriptor, 0]:
        counts[city] = counts.get(city,0) + 1
    most = 0
    for city, count in counts.items():
        if count > most:
            most = count
            A6 = city
    return A6
    #End
    
Descriptor = 'Loud Music/Party'
print('Party city is', whichCity(Descriptor, Times, Requests, Locations, Coordinates))

Party city is New York


In [13]:
#Q9

In [15]:
def longestTimeWithNoRequests(word, times, requests, locations, coordinates):

    boolean = []
    for complaint in requests[:,0]:
        if word in complaint: 
            boolean.append(True)
        else: 
            boolean.append(False)
                       
    
    longest_run = 0

    lrph = np.bincount(times[boolean,0]*24 + times[boolean,1])
    print(lrph)

    run = 0
    for l in lrph:
        if l == 0:
            run += 1
            if run > longest_run:
                longest_run = run
        else:
            run = 0
    return longest_run


Word = 'Noise'
print('Longest run of quiet is', longestTimeWithNoRequests(Word, Times, Requests, Locations, Coordinates), 'hours.')

[33 45 23  8 10  4  2  3  3  9  3 12  9 18 14 22 19 15 13 14 17 17 43 55
 59 53 22 21  9  6  1  0  1  6  4  8  9 15 22 11  5  7 12  7 11 12 15 18
 14 17  9  3  4  0  3  4  3  4  2  3  1  3  0  3  4  3  5  9  7 10 14 17
 13  8  5  1  0  1  0  3  3  6  5  1  5  3  3  2  3  5  5  6  5 16 17 16
 17 16  6  2  2  1  3  1  5  2  6  5  2  1  3  7  4  5  4  6  7 10 14 14
 13 19  6  1  5  3  2  0  4  2  0  1  0  3  1  3  2  5  8  6  3 16 25 29
 24 24  7  3  3  1  3  0  1  2  1  3  4  3  1  2  0  0  3  0  0  0  0  5
  1  2  0  1  0  0  0  0  0  0  1  2  0  0  0  3  5  6  5 10 12 17 28 38
 44 40 26 11 14  7  6  3  1  3  4  5  4  9  9  8 10 17 18 16 10  9 28 20
 21 10  9  8  4  0  3  1  3  4  5  6  5  4  3  6  3  6  3 11 11  9 20 26
 17  8  5  3  1  2  3 11 10  6  3  3  4  4  4  3  3  3  4  7  6 13 21 18
 17 10  4  2  2  0  1  1  2  6  6  6  2  5  2  4  4  3  1 10 22 11 16 33
 30 15  9  3  3  5  3  2  7  1  3  0  9  1  3  7  9  4  6 13  8 15 20 31
 22 14 14  7  3  1  3  0  2  2  2  4  3  6  9  1  9

In [16]:
def averageNumberPartiesEachDayOfWeek(descriptor, times, requests, locations, coordinates):


    isLoud = requests[:,1] == descriptor
    
    dailyevents = np.bincount(times[isLoud,2])
    print(dailyevents)
    
    # 
    ndays = np.zeros(7)
    for d in range(len(ndays)): 
        ndays[d] = len(set(times[times[:,2]==d, 0]))
        # we want to loop through each day of the week 
        #and our day of the week corresponds to the zeros in ndays 
        # we care about the number of days so now we want to reflect back on the first column
        # which has each individual day in there 
        
    #ndays = np.bincount(np.unique(times[:,2]))
    print(ndays)
    # print(dailyevents)
    # print(ndays)
    A10 = dailyevents / ndays
    return A10
  

Descriptor = 'Loud Music/Party'
print('Average parties each day of the week is', 
      averageNumberPartiesEachDayOfWeek(Descriptor, Times, Requests, Locations, Coordinates))

[280 234 325 252 270 810 830]
[4. 4. 4. 3. 3. 4. 4.]
Average parties each day of the week is [ 70.    58.5   81.25  84.    90.   202.5  207.5 ]
